services:
  backend:
    build:
      context: .
      dockerfile: docker/backend.Dockerfile
    ports:
      - "3001:3001"
    env_file:
      - backend/.env.production
    volumes:
      - ./backend:/app/backend  # 挂载整个后端目录，支持热更新
      - ./logs:/app/logs
      - ./uploads:/app/uploads
    # 启动 uvicorn 服务器的命令
    # --reload: 开发模式下启用热重载,代码修改后自动重启
    # --timeout-keep-alive 120: 保持连接超时时间为120秒
    # --timeout-graceful-shutdown 120: 优雅关闭超时时间为120秒
    command: uvicorn main:app --host 0.0.0.0 --port 3001 --reload --timeout-keep-alive 300 --timeout-graceful-shutdown 300
    environment:
      - PYTHONPATH=/app  # 设置 Python 路径
      - PYTHONUNBUFFERED=1
    networks:
      - app-network

networks:
  app-network:
    name: blog-network
    external: true 