# 预生产环境compose配置
services:
  nginx:
    build:
      context: .
      dockerfile: docker/nginx_aliyun.Dockerfile
    ports:
      - "3000:80"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf:ro
      - frontend_build:/usr/share/nginx/html:ro
      - ./logs/nginx:/var/log/nginx:rw
    depends_on:
      frontend:
        condition: service_completed_successfully
    networks:
      - app-network
    # 容器重启策略:
    # unless-stopped - 除非手动停止,否则容器会在退出后自动重启
    # 这与 always 的区别是:
    # - always 会在 Docker daemon 重启时也重启容器
    # - unless-stopped 只有在容器异常退出时才重启,手动停止的容器在 daemon 重启时不会启动
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 500M
    environment:
      - TZ=Asia/Shanghai
      - LANG=C.UTF-8
      - LC_ALL=C.UTF-8
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  frontend:
    build:
      context: .
      dockerfile: docker/frontend_aliyun.Dockerfile
    volumes:
      - frontend_build:/app/dist:rw
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 4G
        reservations:
          memory: 2G
    environment:
      - NODE_ENV=production
      # 增加Node.js内存限制到3GB，确保大型项目构建不会出现内存问题
      - NODE_OPTIONS="--max-old-space-size=3072"
      - TZ=Asia/Shanghai
      - LANG=C.UTF-8
      - LC_ALL=C.UTF-8
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  backend:
    build:
      context: .
      dockerfile: docker/backend_aliyun.Dockerfile
    expose:
      - "3001"
    env_file:
      - backend/.env.production
    volumes:
      - ./logs:/app/logs:rw
      - ./output:/app/output:rw
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    restart: unless-stopped
    networks:
      - app-network
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 2G
        reservations:
          memory: 1G
    command: uvicorn backend.main:app --host 0.0.0.0 --port 3001 --workers 4 --timeout-keep-alive 300 --timeout-graceful-shutdown 300
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
      - ENVIRONMENT=pre
      - TZ=Asia/Shanghai
      - LANG=C.UTF-8
      - LC_ALL=C.UTF-8
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  app-network:
    name: blog-network
    external: true

volumes:
  frontend_build:
    driver: local
  logs:
    driver: local
  output:
    driver: local
